# Generated by Django 3.0.8 on 2020-07-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200707_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registers',
            field=models.ManyToManyField(to='agenda.RegisterDetails'),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
